# -*- mode: python ; coding: utf-8 -*-
# AutoDock Suite Pro — PyInstaller Spec

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[
        ('C:/Users/Administrator/Downloads/Docking Automation/bin/vina.exe', 'bin'),
        ('C:/Users/Administrator/Downloads/Docking Automation/bin/vina_split.exe', 'bin'),
        ('C:/Users/Administrator/Downloads/Docking Automation/bin/autodock4.exe', 'bin'),
        ('C:/Users/Administrator/Downloads/Docking Automation/bin/autogrid4.exe', 'bin'),
        ('C:/Users/Administrator/Downloads/Docking Automation/bin/obabel.exe', 'bin')
    ],
    datas=[
        ('C:/Users/Administrator/AppData/Roaming/Python/Python314/site-packages/customtkinter', 'customtkinter'),
        ('project_config.toml', '.'),
        ('C:/Users/Administrator/Downloads/Docking Automation/gui/assets', 'gui/assets'),
        ('C:/Users/Administrator/AppData/Roaming/Python/Python314/site-packages/meeko/data', 'meeko/data'),
        ('C:/Users/Administrator/AppData/Roaming/Python/Python314/site-packages/openbabel/bin', 'openbabel/bin'),
        ('C:/Users/Administrator/AppData/Roaming/Python/Python314/site-packages/openbabel/bin', 'openbabel/lib/openbabel/3.2.1'),
        ('C:/Users/Administrator/AppData/Roaming/Python/Python314/site-packages/openbabel/bin/data', 'openbabel/bin/data'),
        ('C:/Users/Administrator/AppData/Roaming/Python/Python314/site-packages/openbabel/bin/data', 'openbabel/share/openbabel/3.2.1'),
        ('C:/Users/Administrator/AppData/Roaming/Python/Python314/site-packages/openbabel/bin/data', 'bin/data'),
        ('C:/Users/Administrator/Downloads/Docking Automation/bin', 'bin'),
        ('C:/Users/Administrator/Downloads/Docking Automation/bin', '_internal/bin'),
        ('C:/Users/Administrator/Downloads/Docking Automation/bin/data', 'bin/data'),
        ('C:/Users/Administrator/Downloads/Docking Automation/bin/data', '_internal/bin/data')
    ],
    hiddenimports=[
        'customtkinter',
        'tkinterweb',
        'PySide6',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.QtWebEngineWidgets',
        'PySide6.QtSvgWidgets',
        'PySide6.QtSvg',
        'openpyxl',
        'interactions',
        'depiction',
        'dlg_extract',
        'viewer_3d',
        'pymol_exporter',
        'gui',
        'gui.app',
        'gui.themes',
        'gui.widgets',
        'gui.settings',
        'gui.workspace_tab',
        'gui.preparation_tab',
        'gui.grid_tab',
        'gui.library_tab',
        'gui.runner_tab',
        'gui.results_tab',
        'gui.interaction_diagram',
        'gui_qt',
        'gui_qt.app',
        'gui_qt.styles',
        'gui_qt.workspace_tab',
        'gui_qt.preparation_tab',
        'gui_qt.grid_tab',
        'gui_qt.library_tab',
        'gui_qt.runner_tab',
        'gui_qt.results_tab',
        'gui_qt.comparison_tab',
        'gui_qt.settings_tab',
        'workflow_service',
        'complex_builder',
        'process_manager',
        'rename_ligands',
        'vina_workflow',
        'autodock4_workflow',
        'job_manager',
        'reporting',
        'validators',
        'vina_parser',
        'vina_splitter',
        'prepare',
        'executables',
        'config',
        'models',
        'logging_utils',
        'meeko',
        'rdkit',
        'rdkit.Chem',
        'rdkit.Chem.AllChem',
        'rdkit.Chem.Descriptors',
        'rdkit.Chem.Lipinski',
        'rdkit.Chem.Draw',
        'openbabel',
        'openbabel.pybel',
        'scipy',
        'scipy.spatial',
        'numpy',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter.test', 'matplotlib', 'torch', 'IPython'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='AutoDockSuitePro',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='gui/assets/app_icon.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='AutoDockSuitePro',
)
