#!/usr/bin/env python3
"""
AutoDock Suite Pro — Preparation Helper
=========================================
Auto-generates missing Vina config.txt files and AutoDock4 GPF files
for all receptors in the receptor directory.

Usage (via main.py):
    python main.py --prepare                         # Vina config.txt for all receptors
    python main.py --prepare --engine VINA           # same
    python main.py --prepare --engine AUTODOCK4      # GPF + DPF stubs for all receptors

Usage (standalone):
    python prepare.py --config project_config.toml
    python prepare.py --config project_config.toml --engine AUTODOCK4
"""

from __future__ import annotations

import logging
import shutil
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger("docking_automation.prepare")


def _assert_generated_pdbqt(path: Path) -> None:
    """Reject malformed newly generated PDBQT before exposing it downstream."""
    from validators import validate_pdbqt
    valid, errors = validate_pdbqt(path)
    if not valid:
        raise RuntimeError(
            f"Generated PDBQT failed fixed-column validation: {path}: "
            + "; ".join(errors[:4])
        )

DEFAULT_CLEANUP_COMPONENTS = frozenset({"HOH", "WAT", "H2O", "EDO", "GOL", "SO4", "PO4", "DMS"})


def cleanup_provenance(source_path: Path | str, *, cleanup_water: bool = True,
                       removed_keys: Optional[set[tuple[str, str, int]]] = None) -> dict:
    """Return explicit component retention/removal decisions for a preparation."""
    records = parse_hetatm_records(source_path)
    removed_keys = removed_keys or set()
    retained, removed = [], []
    for record in records:
        key = record["key"]
        if key in removed_keys:
            reason = "user_selected_removal"
            removed.append({**record, "decision": "removed", "reason": reason})
        elif cleanup_water and record["resname"] in DEFAULT_CLEANUP_COMPONENTS:
            reason = "default_cleanup_rule"
            removed.append({**record, "decision": "removed", "reason": reason})
        else:
            reason = "retained_by_default"
            retained.append({**record, "decision": "retained", "reason": reason})
    return {
        "source": str(Path(source_path)),
        "cleanup_water": cleanup_water,
        "default_cleanup_components": sorted(DEFAULT_CLEANUP_COMPONENTS),
        "input_components": records,
        "retained_components": retained,
        "removed_components": removed,
        "cleanup_rules": {
            "water_and_crystallographic_components": sorted(DEFAULT_CLEANUP_COMPONENTS),
        },
        "user_overrides": sorted([
            {"resname": k[0], "chain": k[1], "residue_seq": k[2]}
            for k in removed_keys
        ], key=lambda x: (x["resname"], x["chain"], x["residue_seq"])),
        "warnings": [],
        "scientific_component_relevance_established": False,
    }

# ═══════════════════════════════════════════════════════════════════════════════
# Vina Config.txt Generation
# ═══════════════════════════════════════════════════════════════════════════════

def write_vina_config(
    config_path: Path,
    center_x: float,
    center_y: float,
    center_z: float,
    size_x: float,
    size_y: float,
    size_z: float,
    exhaustiveness: int = 8,
    num_modes: int = 9,
    energy_range: float = 6.0,
) -> None:
    """Write a Vina-format config.txt file.

    Args:
        config_path: Where to write the file.
        center_x/y/z: Grid box center coordinates (Angstroms).
        size_x/y/z: Grid box dimensions (Angstroms).
        exhaustiveness: Search exhaustiveness.
        num_modes: Maximum number of binding poses.
        energy_range: Maximum energy range (kcal/mol).
    """
    content = (
        f"# AutoDock Vina Configuration File\n"
        f"# Generated by AutoDock Suite Pro\n"
        f"#\n"
        f"# Grid Box Center (Angstroms)\n"
        f"center_x = {center_x:.3f}\n"
        f"center_y = {center_y:.3f}\n"
        f"center_z = {center_z:.3f}\n"
        f"\n"
        f"# Grid Box Size (Angstroms)\n"
        f"size_x = {size_x:.3f}\n"
        f"size_y = {size_y:.3f}\n"
        f"size_z = {size_z:.3f}\n"
        f"\n"
        f"# Search parameters\n"
        f"exhaustiveness = {exhaustiveness}\n"
        f"num_modes = {num_modes}\n"
        f"energy_range = {energy_range:.1f}\n"
    )
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(content, encoding="utf-8")
    logger.info(f"Written: {config_path}")


# ═══════════════════════════════════════════════════════════════════════════════
# Scaffold Folder Structure
# ═══════════════════════════════════════════════════════════════════════════════

RECEPTOR_README = """\
RECEPTOR FOLDER — AutoDock Suite Pro
======================================
Place one subfolder per receptor here. Each subfolder must follow this layout:

  RECEPTOR_NAME/
    rigid/
      receptor.pdbqt     ← Your rigid receptor PDBQT (prepared externally)
    flex/                ← OPTIONAL: only needed for flexible docking
      receptor_rigid.pdbqt  ← Rigid backbone PDBQT  (passed to --receptor)
      receptor_flex.pdbqt   ← Flexible sidechain PDBQT (passed to --flex)
    config.txt           ← Vina grid config (run --prepare to auto-generate)

PREPARATION TOOLS (external — not part of this suite):
  • MGLTools / prepare_receptor4.py  — for receptor PDBQT preparation
  • MGLTools / prepare_flexreceptor4.py — for rigid/flex split
  • OpenBabel / obabel                — alternative preparation tool

AUTO-GENERATE CONFIG.TXT:
  Run: python main.py --prepare
  This will prompt for grid center (x, y, z) and box size for each receptor
  that is missing a config.txt.

FLEXIBLE DOCKING:
  The platform auto-detects FLEXIBLE mode when a 'flex/' subfolder exists
  and contains at least one PDBQT file.
"""

LIGAND_README = """\
LIGANDS FOLDER — AutoDock Suite Pro
=====================================
Place all prepared ligand PDBQT files directly in this folder.
Naming: compound_001.pdbqt, compound_002.pdbqt, etc.

PREPARATION TOOLS (external — not part of this suite):
  • MGLTools / prepare_ligand4.py  — for ligand PDBQT preparation
  • OpenBabel / obabel              — alternative preparation tool

The platform will automatically dock ALL *.pdbqt files in this folder
against ALL receptors in the receptors/ folder.

To select specific ligands, edit 'selected_ligands' in project_config.toml:
  [inputs]
  selected_ligands = ["compound_001", "compound_005"]
"""


def create_scaffold(project_root: Path) -> None:
    """Create the AutoDock Suite Pro project folder scaffold.

    Creates:
        receptors/
            README.txt
            example_receptor/
                rigid/
                    PLACE_RIGID_RECEPTOR_PDBQT_HERE.txt
                flex/
                    PLACE_RIGID_BACKBONE_PDBQT_HERE.txt
                    PLACE_FLEX_SIDECHAIN_PDBQT_HERE.txt
                config.txt         (stub with placeholder values)
        ligands/
            README.txt
    """
    rec_dir = project_root / "receptors"
    lig_dir = project_root / "ligands"
    example_dir = rec_dir / "example_receptor"

    # receptors/README.txt
    rec_dir.mkdir(parents=True, exist_ok=True)
    (rec_dir / "README.txt").write_text(RECEPTOR_README, encoding="utf-8")

    # receptors/example_receptor/rigid/
    rigid_dir = example_dir / "rigid"
    rigid_dir.mkdir(parents=True, exist_ok=True)
    (rigid_dir / "PLACE_RIGID_RECEPTOR_PDBQT_HERE.txt").write_text(
        "Replace this file with your rigid receptor .pdbqt file.\n"
        "Example filename: example_receptor.pdbqt\n",
        encoding="utf-8",
    )

    # receptors/example_receptor/flex/ (optional, shows expected layout)
    flex_dir = example_dir / "flex"
    flex_dir.mkdir(parents=True, exist_ok=True)
    (flex_dir / "PLACE_RIGID_BACKBONE_PDBQT_HERE.txt").write_text(
        "Replace with the RIGID backbone PDBQT (passed to Vina --receptor).\n"
        "Typical name: example_receptor_rigid.pdbqt\n"
        "Prepared with: prepare_flexreceptor4.py -r receptor.pdbqt -s A:315_A:316\n",
        encoding="utf-8",
    )
    (flex_dir / "PLACE_FLEX_SIDECHAIN_PDBQT_HERE.txt").write_text(
        "Replace with the FLEXIBLE sidechain PDBQT (passed to Vina --flex).\n"
        "Typical name: example_receptor_flex.pdbqt\n"
        "Prepared with: prepare_flexreceptor4.py -r receptor.pdbqt -s A:315_A:316\n",
        encoding="utf-8",
    )

    # receptors/example_receptor/config.txt (stub)
    write_vina_config(
        example_dir / "config.txt",
        center_x=0.0, center_y=0.0, center_z=0.0,
        size_x=25.0, size_y=25.0, size_z=25.0,
    )
    # Add a note at the top of the stub config
    stub_config = example_dir / "config.txt"
    existing = stub_config.read_text(encoding="utf-8")
    stub_config.write_text(
        "# EDIT THIS FILE: set the correct grid center and size for your receptor.\n"
        + existing,
        encoding="utf-8",
    )

    # ligands/README.txt
    lig_dir.mkdir(parents=True, exist_ok=True)
    (lig_dir / "README.txt").write_text(LIGAND_README, encoding="utf-8")

    # Output directories & structured results subfolders
    for sub in (
        "results", "results/DLG", "results/DPF", "results/VINA", "results/BSNDVP_RESULTS",
        "DLG", "BSNDVP_RESULTS", "logs", "reports"
    ):
        (project_root / sub).mkdir(parents=True, exist_ok=True)

    # Informational placeholders in results folders
    (project_root / "results/DLG/README.txt").write_text(
        "AutoDock 4 Docking Log Files (.dlg) are placed here automatically after docking.\n",
        encoding="utf-8",
    )
    (project_root / "results/DPF/README.txt").write_text(
        "AutoDock 4 Docking Parameter Files (.dpf) used for docking are placed here.\n",
        encoding="utf-8",
    )
    (project_root / "results/VINA/README.txt").write_text(
        "AutoDock Vina output docking pose PDBQT files are placed here.\n",
        encoding="utf-8",
    )

    # Copy dlg_extract.py into workspace for standalone post-processing
    suite_dlg_extract = Path(__file__).resolve().parent / "dlg_extract.py"
    target_dlg_extract = project_root / "dlg_extract.py"
    if suite_dlg_extract.is_file() and not target_dlg_extract.is_file() and project_root.resolve() != suite_dlg_extract.parent.resolve():
        try:
            shutil.copy2(suite_dlg_extract, target_dlg_extract)
            logger.info(f"Copied dlg_extract.py to workspace: {target_dlg_extract}")
        except Exception as e:
            logger.warning(f"Could not copy dlg_extract.py: {e}")

    # Workspace-local bin directory with bundled tools
    target_bin = project_root / "bin"
    suite_bin = Path(__file__).resolve().parent / "bin"
    has_bin = False
    if suite_bin.is_dir() and project_root.resolve() != suite_bin.parent.resolve():
        try:
            target_bin.mkdir(parents=True, exist_ok=True)
            shutil.copytree(suite_bin, target_bin, dirs_exist_ok=True)
            has_bin = True
            logger.info(f"Copied suite binaries to workspace: {target_bin}")
        except Exception as e:
            logger.warning(f"Could not copy binaries to {target_bin}: {e}")
    elif (project_root / "bin").is_dir():
        has_bin = True

    # Generate full self-contained project_config.toml if not present
    toml_path = project_root / "project_config.toml"
    if not toml_path.is_file():
        try:
            from config import generate_template_config
            generate_template_config(toml_path)
            txt = toml_path.read_text(encoding="utf-8")
            txt = txt.replace('name = "Docking_Project"', f'name = "{project_root.name}"')
            toml_path.write_text(txt, encoding="utf-8")
        except Exception as e:
            logger.warning(f"Could not write template config: {e}")

    print()
    print("=" * 60)
    print("  AUTODOCK SUITE PRO -- SCAFFOLD CREATED")
    print("=" * 60)
    print(f"  {rec_dir / 'README.txt'}")
    print(f"  {example_dir / 'rigid'}  <- place your rigid PDBQT here")
    print(f"  {example_dir / 'flex'}   <- place flex PDBQTs here (optional)")
    print(f"  {example_dir / 'config.txt'}")
    print(f"  {lig_dir / 'README.txt'}")
    if has_bin:
        print(f"  {target_bin}  <- bundled executables (vina, autogrid4, autodock4, obabel)")
    print(f"  {project_root / 'results' / 'DLG'}  <- AutoDock4 DLG files will be saved here")
    print(f"  {project_root / 'results' / 'DPF'}  <- AutoDock4 DPF parameter files")
    print(f"  {toml_path}  <- project configuration")
    print()
    print("  Next steps:")
    print("  1. Copy your receptor PDBQT into receptors/<name>/rigid/")
    print("  2. Copy your ligand PDBQTs into ligands/")
    print("  3. Edit receptors/<name>/config.txt with the correct grid center/size")
    print("     OR run: python main.py --prepare")
    print("  4. Run: python main.py --validate")
    print("  5. Run: python main.py")
    print("=" * 60)


# ═══════════════════════════════════════════════════════════════════════════════
# Interactive Prepare — Vina Config
# ═══════════════════════════════════════════════════════════════════════════════

def _prompt_float(prompt: str, default: float) -> float:
    """Prompt for a float value with a default."""
    try:
        raw = input(f"  {prompt} [{default}]: ").strip()
        return float(raw) if raw else default
    except (ValueError, EOFError):
        return default


def prepare_vina_configs(
    config,  # ProjectConfig
    batch_center: Optional[Tuple[float, float, float]] = None,
    batch_size: Optional[Tuple[float, float, float]] = None,
) -> List[Path]:
    """Auto-generate missing config.txt files for all receptors.

    For each receptor without a config.txt:
        - If auto_generate_config is True AND batch_center/size are set in
          project_config.toml, generate silently.
        - Otherwise, interactively prompt the user for center/size values.

    Returns:
        List of config.txt paths that were created.
    """
    from job_manager import discover_receptors, find_receptor_config

    receptors = discover_receptors(config)
    created: List[Path] = []

    print()
    print("=" * 60)
    print("  AUTODOCK SUITE PRO — PREPARE: VINA CONFIG FILES")
    print("=" * 60)

    for rec_name, rec_dir, mode in receptors:
        existing_config = find_receptor_config(rec_dir, rec_name)
        if existing_config and existing_config.exists():
            print(f"  [SKIP] {rec_name}: config.txt already exists ({existing_config.name})")
            continue

        print(f"\n  [MISSING] {rec_name}: no config.txt found.")

        # Try batch values from config
        if batch_center and batch_size:
            cx, cy, cz = batch_center
            sx, sy, sz = batch_size
            print(f"    Using batch values: center=({cx}, {cy}, {cz}), size=({sx}, {sy}, {sz})")
        else:
            print(f"    Enter grid box parameters for '{rec_name}':")
            print(f"    (Tip: open the receptor in PyMOL or UCSF Chimera to find center)")
            cx = _prompt_float("center_x", 0.0)
            cy = _prompt_float("center_y", 0.0)
            cz = _prompt_float("center_z", 0.0)
            sx = _prompt_float("size_x (Angstroms)", 25.0)
            sy = _prompt_float("size_y (Angstroms)", 25.0)
            sz = _prompt_float("size_z (Angstroms)", 25.0)

        config_path = rec_dir / "config.txt"
        write_vina_config(
            config_path,
            center_x=cx, center_y=cy, center_z=cz,
            size_x=sx, size_y=sy, size_z=sz,
            exhaustiveness=config.exhaustiveness,
            num_modes=config.num_modes,
            energy_range=config.energy_range,
        )
        created.append(config_path)
        print(f"    [OK] Written: {config_path}")

    print()
    print(f"  Done. {len(created)} config.txt file(s) created.")
    print("=" * 60)
    return created


# ═══════════════════════════════════════════════════════════════════════════════
# Prepare — AutoDock4 GPF/DPF
# ═══════════════════════════════════════════════════════════════════════════════

def prepare_ad4_files(config) -> None:
    """Generate GPF stubs for all receptors (AutoDock4 mode).

    Unlike Vina, GPF is generated per receptor+ligand pair at runtime.
    This function generates a receptor-level GPF stub to confirm grid
    parameters, which can be reviewed before running the full workflow.
    """
    from job_manager import discover_receptors, discover_ligands, find_receptor_config
    from autodock4_workflow import generate_gpf, extract_grid_from_config

    receptors = discover_receptors(config)
    ligands = discover_ligands(config)

    if not receptors:
        print("  [WARN] No receptors found. Run --scaffold to create the folder structure.")
        return
    if not ligands:
        print("  [WARN] No ligands found in ligands/ directory.")

    print()
    print("=" * 60)
    print("  AUTODOCK SUITE PRO — PREPARE: AUTODOCK4 GPF FILES")
    print("=" * 60)

    for rec_name, rec_dir, mode in receptors:
        from job_manager import _find_rigid_pdbqt
        rigid_pdbqt = _find_rigid_pdbqt(rec_dir, rec_name)
        if not rigid_pdbqt:
            print(f"  [SKIP] {rec_name}: no rigid PDBQT found in rigid/")
            continue

        config_txt = find_receptor_config(rec_dir, rec_name)
        grid_params = extract_grid_from_config(config_txt)

        # Use a placeholder ligand PDBQT to determine atom types
        # (GPF will be regenerated properly at docking time)
        if ligands:
            lig_name, lig_path = ligands[0]
        else:
            print(f"  [SKIP] {rec_name}: no ligands found — GPF requires ligand atom types.")
            continue

        # Generate GPF in the receptor folder for review
        gpf_path = rec_dir / f"{rec_name}.gpf"
        generate_gpf(
            rigid_pdbqt, lig_path, gpf_path,
            config,
            grid_params["center"], grid_params["size"],
        )
        print(f"  [OK] {rec_name}: GPF written → {gpf_path}")
        print(f"       Grid center: {grid_params['center']}")
        print(f"       Grid size  : {grid_params['size']}")

    print()
    print("  Review the GPF files above, then run:")
    print("  python main.py --engine AUTODOCK4")
    print("=" * 60)


# ═══════════════════════════════════════════════════════════════════════════════
# Molecular Preparation Studio (Python 3 AutoDockTools / PyRx Engine)
# ═══════════════════════════════════════════════════════════════════════════════

def _restore_cif_identity_columns(pdbqt_path: Path, cif_path: Path) -> None:
    """Restore chain/residue/component columns lost by some CIF writers."""
    try:
        import tempfile
        import gemmi
        metadata_path = Path(tempfile.NamedTemporaryFile(suffix=".pdb", delete=False).name)
        try:
            gemmi.read_structure(str(cif_path)).write_pdb(str(metadata_path))
            source = [line for line in metadata_path.read_text(encoding="utf-8", errors="replace").splitlines()
                      if line.startswith(("ATOM", "HETATM"))]
        finally:
            metadata_path.unlink(missing_ok=True)
        records = []
        for line in source:
            try:
                records.append((line, float(line[30:38]), float(line[38:46]), float(line[46:54])))
            except (ValueError, IndexError):
                pass
        if not records:
            return
        rewritten = []
        for line in pdbqt_path.read_text(encoding="utf-8", errors="replace").splitlines():
            if line.startswith(("ATOM", "HETATM")) and len(line) >= 54:
                try:
                    x, y, z = float(line[30:38]), float(line[38:46]), float(line[46:54])
                    source_line = min(records, key=lambda item: (item[1]-x)**2 + (item[2]-y)**2 + (item[3]-z)**2)[0]
                    line = line[:16] + source_line[16:27] + line[27:]
                except (ValueError, IndexError):
                    pass
            rewritten.append(line)
        pdbqt_path.write_text("\n".join(rewritten) + "\n", encoding="utf-8")
    except Exception as exc:
        logger.debug(f"CIF identity restoration unavailable: {exc}")


def prepare_receptor_pdbqt(
    input_file: Path | str,
    output_pdbqt: Path | str,
    cleanup_water: bool = True,
    add_hydrogens: bool = True,
    remove_residue_keys: Optional[set] = None,
    remove_chains: Optional[set] = None,
    mutations: Optional[dict] = None,
    deleted_residues: Optional[set] = None,
    charge_model: str = "kollman",
) -> Path:
    """Prepares a raw macromolecule PDB/CIF file into an AutoDock-ready PDBQT.

    1. Removes whole chains selected in *remove_chains* (e.g. stripping redundant monomer chain).
    2. Removes deleted residues in *deleted_residues* and HETATM records in *remove_residue_keys*.
    3. Applies point mutations / renaming in *mutations* (truncating ALA/GLY sidechains, updating resnames).
    4. Removes water (HOH, WAT) if cleanup_water is True.
    5. Adds polar hydrogens (at physiological pH).
    6. Computes partial charges (ADSP Kollman-style fallback or Gasteiger) and assigns AutoDock 4 atom types.
    7. Saves intermediate edited PDB alongside PDBQT for full inspection.

    Args:
        input_file: Source PDB or CIF file.
        output_pdbqt: Destination PDBQT path.
        cleanup_water: Strip waters and crystallographic salts.
        add_hydrogens: Add necessary hydrogens.
        remove_residue_keys: Set of (resname, chain, resseq) tuples to strip.
        remove_chains: Set of chain IDs (e.g. {'B'}) to completely remove.
        mutations: Dict mapping (chain, resseq) -> target_resname (e.g. {('A', 123): 'ALA'}).
        deleted_residues: Set of (chain, resseq) tuples to remove entirely.
        charge_model: 'kollman' (ADSP Kollman-style fallback; not canonical ADT/MGLTools) or 'gasteiger'.

    Returns:
        Resolved Path to output PDBQT.
    """
    in_path = Path(input_file).resolve()
    out_path = Path(output_pdbqt).resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    _remove_keys: set = remove_residue_keys or set()
    _remove_chains: set = {str(c).strip().upper() for c in (remove_chains or set())}
    _deleted_residues: set = {(str(c).strip().upper(), int(s)) for (c, s) in (deleted_residues or set())}
    _mutations: dict = {(str(c).strip().upper(), int(s)): str(m).strip().upper() for (c, s), m in (mutations or {}).items()}

    # Backbone atoms preserved when mutating to ALA or GLY
    ALA_BACKBONE_ATOMS = {"N", "CA", "C", "O", "CB", "H", "HN", "HA", "OXT"}
    GLY_BACKBONE_ATOMS = {"N", "CA", "C", "O", "H", "HN", "HA", "HA1", "HA2", "OXT"}

    WATER_NAMES = DEFAULT_CLEANUP_COMPONENTS

    if not in_path.is_file():
        raise FileNotFoundError(f"Receptor file not found: {in_path}")

    # Step 1: Cleanly filter PDB lines (remove chains, deleted residues, waters, HETATMs, apply mutations)
    raw_lines = in_path.read_text(encoding="utf-8", errors="replace").splitlines()
    clean_lines = []
    for line in raw_lines:
        if line.startswith(("ATOM", "HETATM")):
            atom_name = line[12:16].strip()
            res_name = line[17:20].strip().upper()
            chain = (line[21:22].strip() or "A").upper()
            res_seq_str = line[22:26].strip()
            res_seq = int(res_seq_str) if res_seq_str.isdigit() else 0

            # 1. Filter out whole removed chains
            if chain in _remove_chains:
                continue

            # 2. Filter out deleted residues
            if (chain, res_seq) in _deleted_residues:
                continue

            # 3. Filter out water if requested
            if cleanup_water and res_name in WATER_NAMES:
                continue

            # 4. Filter out specific HETATM entries
            het_key = (res_name, chain, res_seq)
            if het_key in _remove_keys:
                continue

            # 5. Apply point mutations / renaming
            res_key = (chain, res_seq)
            if res_key in _mutations:
                target_res = _mutations[res_key]
                if target_res == "ALA":
                    if atom_name not in ALA_BACKBONE_ATOMS:
                        continue  # Truncate sidechain beyond CB
                    line = line[:17] + f"{target_res:>3s}" + line[20:]
                elif target_res == "GLY":
                    if atom_name not in GLY_BACKBONE_ATOMS:
                        continue  # Truncate sidechain beyond CA
                    line = line[:17] + f"{target_res:>3s}" + line[20:]
                else:
                    line = line[:17] + f"{target_res:>3s}" + line[20:]

            clean_lines.append(line)
        elif line.startswith("TER"):
            ter_chain = (line[21:22].strip() or "").upper()
            if ter_chain and ter_chain in _remove_chains:
                continue
            clean_lines.append(line)
        elif line.startswith(("END", "CONECT")):
            clean_lines.append(line)

    clean_pdb_str = "\n".join(clean_lines) + "\n"

    # Save intermediate cleaned & edited PDB file
    edited_pdb = out_path.parent / f"{out_path.stem}_edited.pdb"
    if out_path.parent.name == "rigid":
        edited_pdb = out_path.parent.parent / f"{out_path.stem}_edited.pdb"
    try:
        edited_pdb.write_text(clean_pdb_str, encoding="utf-8")
        logger.info(f"Saved intermediate edited PDB: {edited_pdb}")
    except Exception:
        pass

    # Step 2: Try OpenBabel CLI
    converted = False
    try:
        from executables import resolve_executable
        ob_exe = resolve_executable(None, "obabel.exe")
        if ob_exe and ob_exe.is_file():
            import tempfile, subprocess
            with tempfile.NamedTemporaryFile(suffix=".pdb", mode="w", encoding="utf-8", delete=False) as tf:
                tf.write(clean_pdb_str)
                tmp_pdb = Path(tf.name)
            try:
                # CIF/mmCIF must be passed to OpenBabel as CIF. Treating CIF
                # text as PDB silently corrupts columns and coordinates.
                input_format = "cif" if in_path.suffix.lower() in (".cif", ".mmcif") else "pdb"
                source_path = in_path if input_format == "cif" else tmp_pdb
                if input_format == "cif":
                    # Prefer gemmi for mmCIF -> PDB normalization.  It
                    # preserves author chain/residue identifiers that can be
                    # lost by direct OpenBabel conversion.  OpenBabel remains
                    # the PDBQT writer and is retained as the fallback when
                    # gemmi is unavailable or cannot read the input.
                    normalized_pdb = Path(tempfile.NamedTemporaryFile(suffix=".pdb", delete=False).name)
                    normalize = None
                    try:
                        import gemmi
                        structure = gemmi.read_structure(str(source_path))
                        structure.write_pdb(str(normalized_pdb))
                        normalize_ok = normalized_pdb.is_file() and normalized_pdb.stat().st_size > 100
                    except Exception as gemmi_err:
                        logger.debug(f"gemmi CIF normalization failed ({gemmi_err}); trying OpenBabel")
                        normalize = subprocess.run(
                            [str(ob_exe), "-icif", str(source_path), "-opdb", "-O", str(normalized_pdb)],
                            capture_output=True, text=True, timeout=30,
                        )
                        normalize_ok = normalize.returncode == 0 and normalized_pdb.is_file()
                    if normalize_ok:
                        # OpenBabel may emit ``*`` for the element column on
                        # CIF records. Recover unambiguous elemental symbols
                        # from atom/residue names before PDBQT typing.
                        normalized_lines = []
                        for normalized_line in normalized_pdb.read_text(encoding="utf-8", errors="replace").splitlines():
                            if normalized_line.startswith(("ATOM", "HETATM")):
                                residue_name = normalized_line[17:20].strip().upper()
                                if cleanup_water and residue_name in WATER_NAMES:
                                    continue
                            if normalized_line.startswith(("ATOM", "HETATM")):
                                atom_name = normalized_line[12:16].strip().upper()
                                residue_name = normalized_line[17:20].strip().upper()
                                inferred = ""
                                for candidate in (atom_name, residue_name):
                                    if candidate in {"ZN", "FE", "MG", "MN", "CA", "CU", "CO", "NI", "HG", "MO"}:
                                        inferred = candidate.title()
                                        break
                                if inferred:
                                    normalized_line = normalized_line[:76] + f"{inferred:>2s}" + normalized_line[78:]
                            normalized_lines.append(normalized_line)
                        normalized_pdb.write_text("\n".join(normalized_lines) + "\n", encoding="utf-8")
                        source_path = normalized_pdb
                        input_format = "pdb"
                cmd = [str(ob_exe), f"-i{input_format}", str(source_path), "-opdbqt", "-O", str(out_path), "--partialcharge", "gasteiger", "-xr"]
                res = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
                if out_path.is_file() and out_path.stat().st_size > 100:
                    # Preserve explicit metal atom types when OpenBabel leaves
                    # the PDBQT AutoDock type column blank for CIF-derived
                    # records.
                    typed_lines = []
                    source_atom_lines = []
                    if in_path.suffix.lower() in (".cif", ".mmcif"):
                        try:
                            import gemmi
                            metadata_pdb = Path(tempfile.NamedTemporaryFile(suffix=".pdb", delete=False).name)
                            gemmi.read_structure(str(in_path)).write_pdb(str(metadata_pdb))
                            source_atom_lines = [
                                line for line in metadata_pdb.read_text(encoding="utf-8", errors="replace").splitlines()
                                if line.startswith(("ATOM", "HETATM"))
                            ]
                        except Exception:
                            source_atom_lines = []
                        finally:
                            try:
                                metadata_pdb.unlink(missing_ok=True)
                            except Exception:
                                pass
                    if not source_atom_lines and input_format == "pdb" and 'normalized_pdb' in locals() and normalized_pdb.is_file():
                        source_atom_lines = [
                            line for line in normalized_pdb.read_text(encoding="utf-8", errors="replace").splitlines()
                            if line.startswith(("ATOM", "HETATM"))
                        ]
                    source_records = []
                    for source_line in source_atom_lines:
                        try:
                            source_records.append((
                                source_line,
                                source_line[12:16].strip().upper(),
                                float(source_line[30:38]), float(source_line[38:46]), float(source_line[46:54]),
                            ))
                        except (ValueError, IndexError):
                            continue
                    # Metadata transfer is intentionally best-effort; the
                    # source records are only used to restore identity fields.
                    for output_line in out_path.read_text(encoding="utf-8", errors="replace").splitlines():
                        if output_line.startswith(("ATOM", "HETATM")) and len(output_line) >= 79:
                            # OpenBabel can rewrite all CIF-derived records as
                            # chain B/residue 0.  Transfer only the structural
                            # identity columns from the metadata-preserving
                            # normalized PDB; coordinates, charges, and AD4
                            # typing remain those generated by OpenBabel.
                            source_line = None
                            try:
                                ox, oy, oz = float(output_line[30:38]), float(output_line[38:46]), float(output_line[46:54])
                                oname = output_line[12:16].strip().upper()
                                candidates = [r for r in source_records if r[1] == oname] or source_records
                                if candidates:
                                    source_line = min(candidates, key=lambda r: (r[2]-ox)**2 + (r[3]-oy)**2 + (r[4]-oz)**2)[0]
                            except (ValueError, IndexError):
                                pass
                            if source_line is not None:
                                if len(source_line) >= 27:
                                    output_line = (
                                        output_line[:16] + source_line[16:27] + output_line[27:]
                                    )
                            atom_name = output_line[12:16].strip().upper()
                            residue_name = output_line[17:20].strip().upper()
                            inferred_type = next((candidate.title() for candidate in (atom_name, residue_name)
                                                  if candidate in {"ZN", "FE", "MG", "MN", "CA", "CU", "CO", "NI", "HG", "MO"}), None)
                            if inferred_type:
                                output_line = output_line[:77] + f"{inferred_type:>2s}" + output_line[79:]
                        typed_lines.append(output_line)
                    out_path.write_text("\n".join(typed_lines) + "\n", encoding="utf-8")
                    if in_path.suffix.lower() in (".cif", ".mmcif"):
                        _restore_cif_identity_columns(out_path, in_path)
                    converted = True
                if 'normalized_pdb' in locals():
                    normalized_pdb.unlink(missing_ok=True)
            finally:
                try:
                    tmp_pdb.unlink(missing_ok=True)
                except Exception:
                    pass
    except Exception as ob_cmd_err:
        logger.debug(f"obabel CLI conversion failed ({ob_cmd_err}), trying pybel...")

    # Step 3: Try OpenBabel pybel on clean PDB text if CLI failed
    if not converted:
        try:
            from openbabel import pybel
            input_format = "cif" if in_path.suffix.lower() in (".cif", ".mmcif") else "pdb"
            mol = pybel.readstring(input_format, in_path.read_text(encoding="utf-8", errors="replace") if input_format == "cif" else clean_pdb_str)
            if add_hydrogens:
                try:
                    mol.addh()
                except Exception:
                    pass
            pdbqt_content = mol.write("pdbqt", opt={"r": None})
            if pdbqt_content and len(pdbqt_content.strip()) > 50:
                out_path.write_text(pdbqt_content, encoding="utf-8")
                converted = True
        except Exception as ob_err:
            logger.debug(f"OpenBabel readstring failed ({ob_err}), using pure Python fallback...")

    # Step 4: Pure Python PDB to PDBQT cleaner fallback
    if not converted:
        out_lines = []
        for line in clean_lines:
            if line.startswith(("ATOM", "HETATM")):
                atom_name = line[12:16].strip()
                element = line[76:78].strip() if len(line) >= 78 else atom_name[0]
                ad_type = element.upper()
                if ad_type in ("C", "A", "N", "NA", "OA", "SA", "HD", "CL", "BR", "F", "I", "P"):
                    pass
                elif element == "O":
                    ad_type = "OA"
                elif element == "N":
                    ad_type = "NA" if "A" in atom_name else "N"
                elif element == "H":
                    ad_type = "HD" if atom_name.startswith(("HN", "HE", "HH", "HD")) else "H"
                pdbqt_line = f"{line[:54]:<54}  1.00 20.00    +0.000 {ad_type:<2s}"
                out_lines.append(pdbqt_line)
            elif line.startswith(("TER", "END")):
                out_lines.append(line)
        out_path.write_text("\n".join(out_lines) + "\n", encoding="utf-8")

    # Step 5: Charge Assignment (ADSP Kollman-style fallback vs Gasteiger)
    if charge_model.lower().startswith("kollman"):
        assign_kollman_charges(out_path)
    else:
        ensure_receptor_has_charges(out_path)

    # Final guard for CIF-derived metal records: charge rewriting can inherit
    # a blank element/type column from OpenBabel, so restore unambiguous AD4
    # metal types from atom and residue names.
    if in_path.suffix.lower() in (".cif", ".mmcif") and out_path.is_file():
        fixed = []
        metal_names = {"ZN", "FE", "MG", "MN", "CA", "CU", "CO", "NI", "HG", "MO"}
        for line in out_path.read_text(encoding="utf-8", errors="replace").splitlines():
            if line.startswith(("ATOM", "HETATM")):
                atom_name = line[12:16].strip().upper()
                residue_name = line[17:20].strip().upper()
                if cleanup_water and residue_name in WATER_NAMES:
                    continue
                metal = next((candidate.title() for candidate in (atom_name, residue_name) if candidate in metal_names), None)
                if metal and len(line) >= 77:
                    line = line[:77] + f"{metal:>2s}" + line[79:]
            fixed.append(line)
        out_path.write_text("\n".join(fixed) + "\n", encoding="utf-8")
        _restore_cif_identity_columns(out_path, in_path)

    _assert_generated_pdbqt(out_path)
    charge_label = "ADSP Kollman-style fallback" if charge_model.lower().startswith("kollman") else "OpenBabel Gasteiger"
    logger.info(f"Prepared receptor PDBQT via {charge_label}: {out_path}")
    return out_path


KOLLMAN_RESIDUE_CHARGES: Dict[str, Dict[str, str]] = {
    "BACKBONE": {
        "N": "-0.350", "H": "+0.275", "HN": "+0.275", "CA": "+0.100", "HA": "0.000",
        "C": "+0.550", "O": "-0.550", "OXT": "-0.800",
    },
    "GLY": {"N": "-0.350", "H": "+0.275", "HN": "+0.275", "CA": "0.000", "HA1": "0.000", "HA2": "0.000", "C": "+0.550", "O": "-0.550"},
    "PRO": {"N": "-0.200", "CD": "+0.100", "CA": "+0.100", "C": "+0.550", "O": "-0.550"},
    "ALA": {"CB": "0.000"},
    "VAL": {"CB": "0.000", "CG1": "0.000", "CG2": "0.000"},
    "LEU": {"CB": "0.000", "CG": "0.000", "CD1": "0.000", "CD2": "0.000"},
    "ILE": {"CB": "0.000", "CG1": "0.000", "CG2": "0.000", "CD1": "0.000"},
    "MET": {"CB": "0.000", "CG": "+0.060", "SD": "-0.120", "CE": "+0.060"},
    "PHE": {"CB": "0.000", "CG": "0.000", "CD1": "0.000", "CD2": "0.000", "CE1": "0.000", "CE2": "0.000", "CZ": "0.000"},
    "TRP": {"CB": "0.000", "CG": "+0.100", "CD1": "+0.100", "CD2": "0.000", "NE1": "-0.400", "HE1": "+0.300", "CE2": "+0.100", "CE3": "0.000", "CZ2": "0.000", "CZ3": "0.000", "CH2": "0.000"},
    "SER": {"CB": "+0.150", "OG": "-0.550", "HG": "+0.400"},
    "THR": {"CB": "+0.150", "OG1": "-0.550", "HG1": "+0.400", "CG2": "0.000"},
    "CYS": {"CB": "+0.100", "SG": "-0.200", "HG": "+0.100"},
    "CYX": {"CB": "+0.100", "SG": "-0.100"},
    "TYR": {"CB": "0.000", "CG": "0.000", "CD1": "0.000", "CD2": "0.000", "CE1": "0.000", "CE2": "0.000", "CZ": "+0.150", "OH": "-0.550", "HH": "+0.400"},
    "ASN": {"CB": "0.000", "CG": "+0.550", "OD1": "-0.550", "ND2": "-0.600", "HD21": "+0.300", "HD22": "+0.300"},
    "GLN": {"CB": "0.000", "CG": "0.000", "CD": "+0.550", "OE1": "-0.550", "NE2": "-0.600", "HE21": "+0.300", "HE22": "+0.300"},
    "ASP": {"CB": "-0.160", "CG": "+0.360", "OD1": "-0.600", "OD2": "-0.600"},
    "GLU": {"CB": "0.000", "CG": "-0.160", "CD": "+0.360", "OE1": "-0.600", "OE2": "-0.600"},
    "HIS": {"CB": "0.000", "CG": "+0.150", "ND1": "-0.400", "HD1": "+0.300", "CD2": "+0.100", "CE1": "+0.200", "NE2": "-0.400", "HE2": "+0.300"},
    "HID": {"CB": "0.000", "CG": "+0.150", "ND1": "-0.400", "HD1": "+0.300", "CD2": "+0.100", "CE1": "+0.200", "NE2": "-0.350"},
    "HIE": {"CB": "0.000", "CG": "+0.150", "ND1": "-0.350", "CD2": "+0.100", "CE1": "+0.200", "NE2": "-0.400", "HE2": "+0.300"},
    "HIP": {"CB": "0.000", "CG": "+0.150", "ND1": "-0.400", "HD1": "+0.350", "CD2": "+0.100", "CE1": "+0.200", "NE2": "-0.400", "HE2": "+0.350"},
    "LYS": {"CB": "0.000", "CG": "0.000", "CD": "0.000", "CE": "+0.210", "NZ": "-0.300", "HZ1": "+0.330", "HZ2": "+0.330", "HZ3": "+0.330"},
    "ARG": {"CB": "0.000", "CG": "0.000", "CD": "+0.100", "NE": "-0.400", "HE": "+0.300", "CZ": "+0.500", "NH1": "-0.450", "HH11": "+0.350", "HH12": "+0.350", "NH2": "-0.450", "HH21": "+0.350", "HH22": "+0.350"},
}


def assign_kollman_charges(pdbqt_path: Path | str) -> bool:
    """Assign ADSP's Kollman-style fallback charges; not canonical ADT/MGLTools."""
    path = Path(pdbqt_path)
    if not path.is_file():
        return False

    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    fixed_lines = []
    for line in lines:
        if line.startswith(("ATOM", "HETATM")):
            atom_name = line[12:16].strip()
            res_name = line[17:20].strip().upper()
            element = line[76:78].strip() if len(line) >= 78 else atom_name[0]
            ad_type = line[77:79].strip() if len(line) >= 79 else element.upper()
            if not ad_type:
                ad_type = element.upper()

            # Look up Kollman charge by residue, then backbone
            chg = None
            if res_name in KOLLMAN_RESIDUE_CHARGES:
                chg = KOLLMAN_RESIDUE_CHARGES[res_name].get(atom_name)
            if not chg:
                chg = KOLLMAN_RESIDUE_CHARGES["BACKBONE"].get(atom_name)
            if not chg:
                # Default generic united-atom polar/nonpolar charges
                if element.upper() == "C":
                    chg = "0.000"
                elif element.upper() in ("O", "OA"):
                    chg = "-0.550"
                elif element.upper() in ("N", "NA"):
                    chg = "-0.350"
                elif element.upper() in ("H", "HD"):
                    chg = "+0.275"
                else:
                    chg = "0.000"

            fixed_lines.append(f"{line[:54]:<54}  1.00 20.00    {float(chg):+6.3f} {ad_type:<2s}")
        else:
            fixed_lines.append(line)

    path.write_text("\n".join(fixed_lines) + "\n", encoding="utf-8")
    return True


def ensure_receptor_has_charges(pdbqt_path: Path | str) -> bool:
    """Ensure receptor PDBQT has valid partial atomic charges required by AutoGrid4.

    If all partial charges are 0.000, assigns realistic standard charges.
    """
    path = Path(pdbqt_path)
    if not path.is_file():
        return False

    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    has_charge = False
    atom_count = 0
    for line in lines:
        if line.startswith(("ATOM", "HETATM")) and len(line) >= 68:
            atom_count += 1
            charge_str = line[66:76].strip() if len(line) >= 76 else line[54:68].strip()
            try:
                chg = float(charge_str.split()[0])
                if abs(chg) > 1e-4:
                    has_charge = True
                    break
            except Exception:
                pass

    if has_charge or atom_count == 0:
        return True

    STD_CHARGES = {
        "N": "-0.350", "CA": "+0.100", "C": "+0.250", "O": "-0.270",
        "HN": "+0.160", "H": "+0.160", "HA": "+0.000",
        "OD1": "-0.270", "OD2": "-0.270", "OE1": "-0.270", "OE2": "-0.270",
        "OG": "-0.200", "OG1": "-0.200", "OH": "-0.200", "SG": "-0.100",
        "NZ": "-0.060", "NE": "-0.100", "NH1": "-0.100", "NH2": "-0.100",
        "ND1": "-0.100", "ND2": "-0.100",
    }
    fixed_lines = []
    for line in lines:
        if line.startswith(("ATOM", "HETATM")):
            atom_name = line[12:16].strip()
            element = line[76:78].strip() if len(line) >= 78 else atom_name[0]
            chg = STD_CHARGES.get(atom_name)
            if not chg:
                chg = "+0.050" if element.upper() == "C" else ("-0.200" if element.upper() in ("O", "N", "S") else "+0.100")
            ad_type = line[77:79].strip() if len(line) >= 79 else element.upper()
            if not ad_type:
                ad_type = element.upper()
            fixed_lines.append(f"{line[:54]:<54}  1.00 20.00    {chg} {ad_type:<2s}")
        else:
            fixed_lines.append(line)

    path.write_text("\n".join(fixed_lines) + "\n", encoding="utf-8")
    logger.info(f"Assigned partial atomic charges to {path} for AutoGrid4 compatibility")
    return True


def prepare_ligand_pdbqt(
    input_file: Path | str,
    output_pdbqt: Path | str,
    generate_3d: bool = True,
) -> Dict[str, Any]:
    """Prepares small molecule (SDF/MOL2/PDB/SMI) into a flexible ligand PDBQT.

    Uses Scripps Meeko with RDKit conformer generation, or OpenBabel fallback.

    Args:
        input_file: Path to input structure or SMILES string.
        output_pdbqt: Destination PDBQT path.
        generate_3d: Generate 3D conformer if 2D or SMILES.

    Returns:
        Dictionary of molecular descriptors and preparation metadata.
    """
    in_path = Path(input_file)
    out_path = Path(output_pdbqt)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    def _metal_diagnostics(path: Path) -> Dict[str, Any]:
        try:
            from ad4_compatibility import METAL_REGISTRY, extract_atom_types
            types = extract_atom_types(path)
            metals = []
            for atom_type in types:
                record = METAL_REGISTRY.get(atom_type)
                if record:
                    metals.append({
                        "element": record.element,
                        "atom_type": atom_type,
                        "standard_ad4": record.standard_ad4_parameterized,
                        "specialized_workflows": [record.specialized_workflow] if record.specialized_workflow else [],
                    })
            return {
                "detected": metals,
                "status": "SUPPORTED WITH LIMITATIONS" if metals else "ORDINARY_ORGANIC_LIGAND",
                "requires_user_review": bool(metals),
                "note": "Metal-containing ligands require explicit review of component connectivity, charges, and torsion handling.",
            }
        except Exception as exc:
            return {"detected": [], "status": "UNKNOWN", "requires_user_review": True, "error": str(exc)}

    # 1. Try Scripps Meeko + RDKit
    try:
        import meeko
        from rdkit import Chem
        from rdkit.Chem import AllChem

        ext = in_path.suffix.lstrip(".").lower()
        rd_mol = None

        if ext in ("sdf", "mol"):
            suppl = Chem.SDMolSupplier(str(in_path), removeHs=False)
            rd_mol = next(suppl, None)
        elif ext == "mol2":
            rd_mol = Chem.MolFromMol2File(str(in_path), removeHs=False)
            if rd_mol is None:
                try:
                    rd_mol = Chem.MolFromMol2File(str(in_path), removeHs=False, sanitize=False)
                    if rd_mol is not None:
                        rd_mol.UpdatePropertyCache(strict=False)
                except Exception:
                    rd_mol = None
        elif ext == "pdb":
            rd_mol = Chem.MolFromPDBFile(str(in_path), removeHs=False)
        elif ext in ("smi", "smiles", "txt"):
            smi_text = in_path.read_text(encoding="utf-8").strip().split()[0]
            rd_mol = Chem.MolFromSmiles(smi_text)

        if rd_mol is not None:
            rd_mol = Chem.AddHs(rd_mol)
            if generate_3d or rd_mol.GetNumConformers() == 0:
                AllChem.EmbedMolecule(rd_mol, randomSeed=42)
                AllChem.MMFFOptimizeMolecule(rd_mol)

            preparator = meeko.MoleculePreparation()
            mol_setups = preparator.prepare(rd_mol)
            if not mol_setups:
                raise RuntimeError("Meeko preparation returned empty setup list")

            writer_res = meeko.PDBQTWriterLegacy.write_string(mol_setups[0])
            if isinstance(writer_res, tuple):
                pdbqt_str = writer_res[0]
                if len(writer_res) > 1 and not writer_res[1]:
                    err_msg = writer_res[2] if len(writer_res) > 2 else "Unknown error"
                    raise RuntimeError(f"Meeko setup failed: {err_msg}")
            else:
                pdbqt_str = str(writer_res)

            if not pdbqt_str or not pdbqt_str.strip():
                raise RuntimeError("Meeko generated empty PDBQT output")

            out_path.write_text(pdbqt_str, encoding="utf-8")
            _assert_generated_pdbqt(out_path)
            logger.info(f"Prepared ligand PDBQT via Meeko: {out_path}")
            result = calculate_molecule_descriptors(out_path)
            result["metal_diagnostics"] = _metal_diagnostics(out_path)
            try:
                from validators import inspect_pdbqt_charges
                result["charge_diagnostics"] = inspect_pdbqt_charges(out_path)
            except Exception as charge_err:
                result["charge_diagnostics"] = {"status": "UNAVAILABLE", "error": str(charge_err)}
            result["preparation_provenance"] = {
                "backend": "Meeko",
                "input": str(in_path),
                "generate_3d": generate_3d,
                "hydrogens_added": True,
                "reference_coordinates_preserved": not generate_3d,
            }
            return result

    except Exception as meeko_err:
        logger.warning(f"Meeko preparation notice ({meeko_err}), using OpenBabel...")

    # 2. OpenBabel fallback
    try:
        from executables import configure_openbabel_env
        configure_openbabel_env()
        from openbabel import pybel
        ext = in_path.suffix.lstrip(".").lower()
        ob_mol = next(pybel.readfile(ext, str(in_path)))
        ob_mol.addh()
        if generate_3d:
            try:
                if len(ob_mol.atoms) > 0 and ob_mol.atoms[0].coords == (0.0, 0.0, 0.0):
                    ob_mol.make3D()
            except Exception:
                pass
        pdbqt_content = ob_mol.write("pdbqt")
        if not pdbqt_content or not pdbqt_content.strip():
            raise RuntimeError("OpenBabel produced empty PDBQT output")
        out_path.write_text(pdbqt_content, encoding="utf-8")
        _assert_generated_pdbqt(out_path)
        logger.info(f"Prepared ligand PDBQT via OpenBabel: {out_path}")
        result = calculate_molecule_descriptors(out_path)
        result["metal_diagnostics"] = _metal_diagnostics(out_path)
        try:
            from validators import inspect_pdbqt_charges
            result["charge_diagnostics"] = inspect_pdbqt_charges(out_path)
        except Exception as charge_err:
            result["charge_diagnostics"] = {"status": "UNAVAILABLE", "error": str(charge_err)}
        result["preparation_provenance"] = {
            "backend": "OpenBabel",
            "input": str(in_path),
            "generate_3d": generate_3d,
            "hydrogens_added": True,
            "reference_coordinates_preserved": not generate_3d,
        }
        return result
    except Exception as ob_err:
        raise RuntimeError(f"Could not prepare ligand {input_file}: {ob_err}")


def split_flexible_receptor(
    receptor_pdbqt: Path | str,
    flex_residue_names: List[str],
    output_rigid_pdbqt: Path | str,
    output_flex_pdbqt: Path | str,
) -> Tuple[Path, Path]:
    """Splits a rigid receptor PDBQT into a rigid backbone and flexible sidechains pair.

    In AutoDock flexible receptor docking:
      - output_rigid_pdbqt retains non-flexible residues plus N, CA, C, O backbone of target residues.
      - output_flex_pdbqt contains sidechains wrapped in BEGIN_RES / ROOT / BRANCH / END_RES.

    Args:
        receptor_pdbqt: Path to existing receptor PDBQT.
        flex_residue_names: List of target residues (e.g. ['ILE:199', 'TYR:326'] or ['GLN 206']).
        output_rigid_pdbqt: Output path for rigid part.
        output_flex_pdbqt: Output path for flexible part.

    Returns:
        Tuple of (rigid_path, flex_path).
    """
    rec_path = Path(receptor_pdbqt)
    out_rigid = Path(output_rigid_pdbqt)
    out_flex = Path(output_flex_pdbqt)
    out_rigid.parent.mkdir(parents=True, exist_ok=True)
    out_flex.parent.mkdir(parents=True, exist_ok=True)

    # Normalize flex identifiers: extract sequence numbers and names
    flex_targets = set()
    for fr in flex_residue_names:
        clean = fr.replace(":", " ").strip()
        parts = clean.split()
        for p in parts:
            if p.isdigit():
                flex_targets.add(int(p))
            else:
                flex_targets.add(p.upper())

    rigid_lines = []
    flex_blocks: Dict[str, List[str]] = {}

    lines = rec_path.read_text(encoding="utf-8", errors="replace").splitlines()
    for line in lines:
        if line.startswith(("ATOM", "HETATM")):
            res_name = line[17:20].strip().upper()
            chain = line[21:22].strip() or "A"
            res_seq_str = line[22:26].strip()
            res_seq = int(res_seq_str) if res_seq_str.isdigit() else 0
            atom_name = line[12:16].strip().upper()

            is_flex = (res_seq in flex_targets) or (res_name in flex_targets)
            if is_flex:
                res_key = f"{res_name} {chain} {res_seq}"
                # Backbone atoms remain in rigid file
                if atom_name in ("N", "HN", "H", "C", "O"):
                    rigid_lines.append(line)
                else:
                    # CA and sidechain atoms go to flexible block
                    if res_key not in flex_blocks:
                        flex_blocks[res_key] = []
                    flex_blocks[res_key].append(line)
            else:
                rigid_lines.append(line)
        else:
            rigid_lines.append(line)

    # Write flexible PDBQT with valid AutoDock/Vina 1..N atom numbering per residue
    flex_lines = []
    for res_key, atom_lines in flex_blocks.items():
        flex_lines.append(f"BEGIN_RES {res_key}")
        flex_lines.append("ROOT")
        ca_line = None
        cb_line = None
        other_lines = []
        for l in atom_lines:
            if " CA " in l:
                ca_line = l
            elif " CB " in l:
                cb_line = l
            else:
                other_lines.append(l)

        # In AutoDock / Vina PDBQT flex residues, the ROOT contains CA (atom serial 1).
        # The BRANCH starts from atom 1 (CA) to atom 2 (CB).
        # All atoms in the flexible residue must have consecutive serial numbers 1, 2, 3...
        # so that BRANCH 1 2 and any torsional records resolve correctly.
        atom_serial = 1
        if ca_line:
            renumbered_ca = ca_line[:6] + f"{atom_serial:5d}" + ca_line[11:]
            flex_lines.append(renumbered_ca)
        flex_lines.append("ENDROOT")

        branch_atoms = []
        if cb_line:
            atom_serial += 1
            branch_atoms.append(cb_line[:6] + f"{atom_serial:5d}" + cb_line[11:])
        for l in other_lines:
            atom_serial += 1
            branch_atoms.append(l[:6] + f"{atom_serial:5d}" + l[11:])

        if branch_atoms:
            flex_lines.append("BRANCH 1 2")
            flex_lines.extend(branch_atoms)
            flex_lines.append("ENDBRANCH 1 2")
        flex_lines.append(f"END_RES {res_key}")

    out_rigid.write_text("\n".join(rigid_lines) + "\n", encoding="utf-8")
    out_flex.write_text("\n".join(flex_lines) + "\n", encoding="utf-8")

    logger.info(f"Split flexible receptor: {out_rigid} and {out_flex}")
    return (out_rigid, out_flex)


def sanitize_flex_pdbqt(flex_path: Path | str) -> bool:
    """Ensure flexible sidechain PDBQT has continuous 1..N serial numbers per residue matching BRANCH records."""
    p = Path(flex_path)
    if not p.is_file():
        return False
    try:
        lines = p.read_text(encoding="utf-8", errors="replace").splitlines()
        new_lines = []
        modified = False
        atom_idx = 0
        in_res = False

        for l in lines:
            if l.startswith("BEGIN_RES"):
                atom_idx = 0
                in_res = True
                new_lines.append(l)
            elif l.startswith("END_RES"):
                in_res = False
                new_lines.append(l)
            elif in_res and l.startswith(("ATOM", "HETATM")):
                atom_idx += 1
                cur_serial_str = l[6:11].strip()
                cur_serial = int(cur_serial_str) if cur_serial_str.isdigit() else 0
                if cur_serial != atom_idx:
                    modified = True
                    new_lines.append(l[:6] + f"{atom_idx:5d}" + l[11:])
                else:
                    new_lines.append(l)
            else:
                new_lines.append(l)

        if modified:
            p.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
            logger.info(f"Sanitized flexible receptor PDBQT atom indices: {p}")
            return True
    except Exception as e:
        logger.warning(f"Could not sanitize flex PDBQT {p}: {e}")
    return False


def calculate_molecule_descriptors(
    file_path: Path | str,
    obabel_exe: Optional[Path | str] = None,
    **kwargs,
) -> Dict[str, Any]:
    """Calculates physicochemical descriptors for a ligand from PDBQT/SDF/MOL2.

    All descriptors are computed from the 2D molecular graph using RDKit
    (deterministic calculations, no ML models involved).

    Properties and their citation basis:
      mw         — Molecular Weight (standard)
      logp       — Crippen–Wildman LogP (Crippen & Wildman, J Med Chem 1999)
      psa        — Topological Polar Surface Area (Ertl et al., J Med Chem 2000)
      hbd        — H-Bond Donors (Lipinski et al., Adv Drug Deliv Rev 1997)
      hba        — H-Bond Acceptors (Lipinski et al., 1997)
      rot_bonds  — Rotatable Bonds (Veber et al., J Med Chem 2002)
      arom_rings — Aromatic Ring Count (standard RDKit)
      lipinski   — Lipinski Rule of 5 (Lipinski et al., 1997)
                   Criteria: MW≤500, LogP≤5, HBD≤5, HBA≤10
      veber_pass — Veber oral bioavailability rules (Veber et al., 2002)
                   Criteria: PSA≤140 Å², RotBonds≤10
    """
    p = Path(file_path)
    info: Dict[str, Any] = {
        "name": p.stem,
        "stem": p.stem,
        "file_name": p.name,
        "mw": 0.0,
        "logp": 0.0,
        "psa": 0.0,
        "hbd": 0,
        "hba": 0,
        "rot_bonds": 0,
        "arom_rings": 0,
        "aromatic_rings": 0,
        "formula": "",
        "lipinski": "Pass",
        "ro5_pass": True,
        "veber_pass": True,
    }

    if not p.is_file():
        return info

    try:
        from openbabel import pybel
        from rdkit import Chem
        from rdkit.Chem import Descriptors, Lipinski, rdMolDescriptors

        ext = p.suffix.lstrip(".").lower()
        if ext not in ("pdbqt", "sdf", "mol2", "pdb"):
            ext = "pdbqt"

        ob_mol = next(pybel.readfile(ext, str(p)), None)
        if ob_mol:
            info["formula"] = ob_mol.formula
            info["mw"] = round(ob_mol.exactmass, 2)
            try:
                rdmol = Chem.MolFromMolBlock(ob_mol.write("mol"))
                if rdmol:
                    info["mw"] = round(Descriptors.MolWt(rdmol), 2)
                    info["logp"] = round(Descriptors.MolLogP(rdmol), 2)
                    info["psa"] = round(Descriptors.TPSA(rdmol), 2)
                    info["hbd"] = Lipinski.NumHDonors(rdmol)
                    info["hba"] = Lipinski.NumHAcceptors(rdmol)
                    info["rot_bonds"] = Lipinski.NumRotatableBonds(rdmol)
                    n_arom = rdMolDescriptors.CalcNumAromaticRings(rdmol)
                    info["arom_rings"] = n_arom
                    info["aromatic_rings"] = n_arom
            except Exception:
                pass
    except Exception:
        pass

    # Quick PDBQT rotatable bonds fallback if 0
    if info["rot_bonds"] == 0 and p.suffix.lower() == ".pdbqt":
        try:
            with open(p, "r", encoding="utf-8", errors="replace") as f:
                for line in f:
                    if "active torsions" in line:
                        parts = line.strip().split()
                        if len(parts) >= 2 and parts[1].isdigit():
                            info["rot_bonds"] = int(parts[1])
        except Exception:
            pass

    # Lipinski Rule of 5 (≤1 violation permitted per original paper)
    violations = 0
    if info["mw"] > 500:  violations += 1
    if info["logp"] > 5.0: violations += 1
    if info["hbd"] > 5:   violations += 1
    if info["hba"] > 10:  violations += 1
    info["lipinski"] = "Pass" if violations <= 1 else f"Fail ({violations}v)"
    info["ro5_pass"] = (violations <= 1)

    # Veber oral bioavailability criteria (both must be met)
    info["veber_pass"] = (info["psa"] <= 140.0 and info["rot_bonds"] <= 10)
    info["aromatic_rings"] = info.get("arom_rings", 0)

    return info


def inspect_receptor_residues(receptor_path: Path | str) -> List[Dict[str, Any]]:
    """Returns a list of unique residues in a receptor for active-site targeting and flex selection."""
    p = Path(receptor_path)
    if not p.is_file():
        return []

    residues = []
    seen = set()
    with open(p, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            if line.startswith(("ATOM", "HETATM")):
                res_name = line[17:20].strip().upper()
                chain = line[21:22].strip() or "A"
                res_seq_str = line[22:26].strip()
                res_seq = int(res_seq_str) if res_seq_str.isdigit() else 0
                key = (res_name, chain, res_seq)
                if key not in seen:
                    seen.add(key)
                    residues.append({
                        "name": res_name,
                        "chain": chain,
                        "seq": res_seq,
                        "label": f"{res_name} {chain} {res_seq}",
                    })
    return residues

def parse_hetatm_records(pdb_path: Path | str) -> List[Dict[str, Any]]:
    """Parse all unique HETATM entries from a PDB/CIF file for the GUI checklist.

    Returns a list of dicts with keys:
        key      — tuple (resname, chain, resseq) — usable as remove_residue_keys entry
        resname  — e.g. 'SAG'
        chain    — e.g. 'D'
        resseq   — integer sequence number
        label    — human-readable string e.g. 'SAG  D  401'
        is_water — True if this is a water molecule
    """
    WATER_NAMES = {"HOH", "WAT", "H2O"}
    METAL_ELEMENTS = {"MG", "CA", "MN", "FE", "ZN", "CU", "CO", "NI", "HG", "MO"}
    METAL_NAMES = METAL_ELEMENTS | {"MG2", "CA2", "MN2", "FE2", "FE3", "ZN2"}
    COFACTOR_NAMES = {"HEM", "HEME", "NAD", "FAD", "FMN", "SAM", "PLP", "ATP"}
    p = Path(pdb_path)
    if not p.is_file():
        return []

    entries: List[Dict[str, Any]] = []
    seen: set = set()
    metal_elements_by_key: Dict[tuple, set] = {}
    with open(p, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            if not line.startswith("HETATM"):
                continue
            resname = line[17:20].strip().upper()
            element = (line[76:78].strip() if len(line) >= 78 else "").upper()
            chain = line[21:22].strip() or "A"
            res_seq_str = line[22:26].strip()
            resseq = int(res_seq_str) if res_seq_str.isdigit() else 0
            key = (resname, chain, resseq)
            if key in seen:
                if element in METAL_ELEMENTS:
                    metal_elements_by_key.setdefault(key, set()).add(element)
                continue
            seen.add(key)
            metal_elements_by_key[key] = {element} if element in METAL_ELEMENTS else set()
            if resname in WATER_NAMES:
                component_type = "WATER"
            elif element in METAL_ELEMENTS or resname in METAL_NAMES:
                component_type = "METAL"
            elif resname in COFACTOR_NAMES:
                component_type = "COFACTOR"
            else:
                component_type = "UNKNOWN_COMPONENT"
            entries.append({
                "key": key,
                "resname": resname,
                "chain": chain,
                "resseq": resseq,
                "label": f"{resname:<4s} {chain}  {resseq}",
                "is_water": resname in WATER_NAMES,
                "element": element,
                "component_type": component_type,
                "classification_status": "validated_name_or_element" if component_type != "UNKNOWN_COMPONENT" else "user_review_required",
                "metal_elements": sorted(metal_elements_by_key[key]),
            })

    # Sort: waters last, then alphabetical by resname
    entries.sort(key=lambda e: (not e["is_water"], e["resname"], e["resseq"]))
    for entry in entries:
        metals = sorted(metal_elements_by_key.get(entry["key"], set()))
        entry["metal_elements"] = metals
        if metals and entry["component_type"] == "COFACTOR":
            entry["classification_status"] = "cofactor_contains_metal"
    return entries


def parse_pdb_chains(pdb_path: Path | str) -> List[Dict[str, Any]]:
    """Parse all chains present in a PDB/CIF file.

    Returns a list of dicts:
        chain: chain identifier (e.g. 'A')
        atom_count: total ATOM + HETATM count
        residue_count: count of unique residues in this chain
        res_start: first residue sequence number
        res_end: last residue sequence number
        label: formatted summary string e.g. 'Chain A — 1,450 atoms (res 1–295)'
    """
    p = Path(pdb_path)
    if not p.is_file():
        return []

    chains_data: Dict[str, Dict[str, Any]] = {}
    with open(p, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            if line.startswith(("ATOM", "HETATM")):
                chain = (line[21:22].strip() or "A").upper()
                res_seq_str = line[22:26].strip()
                res_seq = int(res_seq_str) if res_seq_str.isdigit() else 0

                if chain not in chains_data:
                    chains_data[chain] = {
                        "chain": chain,
                        "atoms": 0,
                        "residues": set(),
                    }
                chains_data[chain]["atoms"] += 1
                if res_seq != 0:
                    chains_data[chain]["residues"].add(res_seq)

    result = []
    for chain in sorted(chains_data.keys()):
        d = chains_data[chain]
        res_list = sorted(d["residues"])
        res_start = res_list[0] if res_list else 1
        res_end = res_list[-1] if res_list else 1
        n_res = len(res_list)
        label = f"Chain {chain}  -  {d['atoms']:,} atoms ({n_res} residues: {res_start}-{res_end})"
        result.append({
            "chain": chain,
            "atom_count": d["atoms"],
            "residue_count": n_res,
            "res_start": res_start,
            "res_end": res_end,
            "label": label,
        })
    return result


def parse_pdb_residues(pdb_path: Path | str) -> List[Dict[str, Any]]:
    """Parse all amino acid residues from ATOM records in a PDB file for editing and mutation.

    Returns a list of dicts:
        chain: chain ID e.g. 'A'
        seq: sequence number integer e.g. 123
        name: 3-letter residue name e.g. 'ASP'
        atom_count: number of atoms in this residue
        key: tuple (chain, seq)
        label: e.g. 'Chain A : ASP 123 (8 atoms)'
    """
    p = Path(pdb_path)
    if not p.is_file():
        return []

    residues: Dict[Tuple[str, int], Dict[str, Any]] = {}
    with open(p, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            if line.startswith("ATOM"):
                chain = (line[21:22].strip() or "A").upper()
                res_name = line[17:20].strip().upper()
                res_seq_str = line[22:26].strip()
                res_seq = int(res_seq_str) if res_seq_str.isdigit() else 0
                key = (chain, res_seq)
                if key not in residues:
                    residues[key] = {
                        "chain": chain,
                        "seq": res_seq,
                        "name": res_name,
                        "atoms": 0,
                        "key": key,
                    }
                residues[key]["atoms"] += 1

    result = []
    for key, d in sorted(residues.items(), key=lambda kv: (kv[0][0], kv[0][1])):
        d["atom_count"] = d["atoms"]
        d["label"] = f"Chain {d['chain']} : {d['name']:<4s} {d['seq']} ({d['atoms']} atoms)"
        result.append(d)
    return result


def get_coligand_bbox(
    ligand_path: Path | str,
    padding: float = 5.0,
) -> Optional[Dict[str, float]]:
    """Compute bounding-box center and padded size from a ligand SDF/MOL2/PDB.

    Returns a dict with keys: center_x, center_y, center_z, size_x, size_y, size_z
    or None if the file cannot be parsed.

    Args:
        ligand_path: Path to SDF, MOL2, or PDB file.
        padding: Extra Ångströms added on each side of the bounding box.
    """
    p = Path(ligand_path)
    if not p.is_file():
        return None

    coords: List[tuple] = []

    # Try RDKit first
    try:
        from rdkit import Chem
        ext = p.suffix.lower()
        mol = None
        if ext in (".sdf", ".mol"):
            suppl = Chem.SDMolSupplier(str(p), removeHs=True)
            mol = next(suppl, None)
        elif ext == ".mol2":
            mol = Chem.MolFromMol2File(str(p), removeHs=True)
        elif ext == ".pdb":
            mol = Chem.MolFromPDBFile(str(p), removeHs=True)
        if mol and mol.GetNumConformers() > 0:
            conf = mol.GetConformer(0)
            for i in range(mol.GetNumAtoms()):
                pos = conf.GetAtomPosition(i)
                coords.append((pos.x, pos.y, pos.z))
    except Exception:
        pass

    # Fallback: OpenBabel
    if not coords:
        try:
            from openbabel import pybel
            ext = p.suffix.lstrip(".").lower()
            ob_mol = next(pybel.readfile(ext, str(p)), None)
            if ob_mol:
                for atom in ob_mol.atoms:
                    coords.append(atom.coords)
        except Exception:
            pass

    if not coords:
        return None

    xs = [c[0] for c in coords]
    ys = [c[1] for c in coords]
    zs = [c[2] for c in coords]

    cx = (min(xs) + max(xs)) / 2.0
    cy = (min(ys) + max(ys)) / 2.0
    cz = (min(zs) + max(zs)) / 2.0
    sx = (max(xs) - min(xs)) + 2 * padding
    sy = (max(ys) - min(ys)) + 2 * padding
    sz = (max(zs) - min(zs)) + 2 * padding

    return {
        "center_x": round(cx, 3),
        "center_y": round(cy, 3),
        "center_z": round(cz, 3),
        "size_x": round(sx, 3),
        "size_y": round(sy, 3),
        "size_z": round(sz, 3),
    }


def run_prepare(config, engine_override: Optional[str] = None) -> None:
    """Entry point called from main.py --prepare."""
    from models import Engine
    from config import load_config

    engine = config.engine
    if engine_override:
        try:
            engine = Engine(engine_override.upper())
        except ValueError:
            pass

    if engine == Engine.VINA:
        # Try batch values from [prepare] section in config (if set)
        batch_center = None
        batch_size = None
        # (these would come from config if we add them — prompt otherwise)
        prepare_vina_configs(config, batch_center, batch_size)
    else:
        prepare_ad4_files(config)


# ---------------------------------------------------------------------------
# Compatibility Aliases for GUI & External Scripts
# ---------------------------------------------------------------------------
prepare_receptor = prepare_receptor_pdbqt
prepare_ligand = prepare_ligand_pdbqt
scan_pdb_hetatms = parse_hetatm_records
split_receptor_rigid_flex = split_flexible_receptor
calculate_bounding_box = get_coligand_bbox
parse_pdbqt_residues = inspect_receptor_residues


if __name__ == "__main__":
    import argparse

    # Configure UTF-8 output on Windows consoles
    if sys.platform == "win32":
        try:
            sys.stdout.reconfigure(encoding="utf-8", errors="replace")
            sys.stderr.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass

    from config import load_config
    from models import SUITE_BANNER

    parser = argparse.ArgumentParser(
        prog="prepare.py",
        description=f"{SUITE_BANNER} — Preparation Helper",
    )
    parser.add_argument("--config", required=True, type=Path)
    parser.add_argument("--engine", choices=["VINA", "AUTODOCK4"], default=None)
    parser.add_argument("--scaffold", action="store_true",
                        help="Create the folder scaffold structure")
    args = parser.parse_args()

    cfg = load_config(args.config)

    if args.scaffold:
        create_scaffold(cfg.project_root)
    else:
        run_prepare(cfg, args.engine)
